language: node_js
sudo: false
node_js:
  - "lts/*"

cache:
  apt: tru
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --pure-lockfile

script:
  - npm run build

deploy:
  provider: pages
  local-dir: dist
  skip_cleanup: true
  keep-history: true
  committer-from-gh: true
  github-token: $GITHUB_TOKEN

branches:
  only:
    - master
