init:
  - 你好，我是 Mitscherlich
  - 请问你有什么想了解的？

questions:
  school: 能介绍一下你在学校的经历吗？
  edu: 你在学校成绩怎样？
  awards: 你获得过哪些荣誉奖项呢？
  skills: 你都熟悉哪些专业技能？
  habits: 能介绍一下你的兴趣爱好吗？

answers:
  school:
    - 我在学校参加了许多课余活动，比较有代表性的有以下几件：
    - 我曾于 2016 年参加了校党委宣传部下设的长江大学在线信息传媒，受聘担任 "Linux 运维工程师" 一职
      负责学校各学院首页网站部署和维护
    - 我在大二时加入我校教授领导的实验室，担任算法研究员一职
    - 期间组织实验室的同学参加学校大学生创新创业大赛，设计完成了 "智能人脸识别门禁系统" 项目，并获得了校级创意组三等奖
  edu:
    - 我于 2015 年就读于荆州长江大学计算机科学专业
    - 在校期间我成绩良好，稳定于年级前 25%，无任何挂科记录
    - 并且陆续通过了 CET-4、CET-6 考试
    - 我将于 2019 年 6 月份毕业，现在正在完成毕业设计，可以长期稳定实习工作
  awards:
    - 我在 "长大在线" 工作期间曾与同组的同学参加数据挖掘竞赛，协助其完成算法与程序实现
    - 在实验室学习期间，在老师的指导下完成了专利 "基于生物特征的学生信息采集装置" 和
      论文 "光流估计下的移动端实时人脸检测" 的撰写，并发表于 2018 年 4 月份的《计算机应用》杂志上
  skills:
    - 我在校期间通过课程和实习学习了 C/C++、Java 和 Python 语言的使用
    - 在 "长大在线" 工作学习期间，我熟练掌握了 git 的使用，与同学协作开发了许多内部工具，具有良好的团队协作技能
    - 同时我在课余时间也通过自学掌握了 JavaScript、Kotlin 等语言，并掌握了 Node.js 的使用与开发
    - 有了 Node.js 的帮助，我学习了 Express、Koa、Egg 等服务端框架的使用，以及 jQuery、Bootstrap、Vue.js 等
      前端类库和框架的使用
    - 我也用这些工具开发了一些不错的开源项目，例如你正看到的这个页面和我的博客，就都可以在我的 Github 找到，不妨去看看吧~
    - 我的 Github：<a href="https://github.com/Mitscherlich" target="_blank">@Mitscherlich</a>
  habits:
    - 我热爱二次元，热爱 Coding，并且善于用代码解决生活中遇到的问题
    - 我喜欢打羽毛球，在夏天还喜欢游泳
    - 不过最喜欢的运动还是一个人骑自行车在城市中独自旅行

more:
  - 还有更多想要了解的，可以来我的<a href="https://blog.mitscherlich.me">博客</a>或者
    <a href="https://github.com/Mitscherlich" target="_blank">Github</a> 看看！
